version: '3'
services:
  app:
    build: 
      context: ./web
      dockerfile: ../Dockerfile
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=verceldb
    ports:
      - "5480:5432"
  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
volumes:
  minio_data:
